### ISSUE TITLE
remove "merge-descriptors" dependency at all?

### ISSUE THREAD

**Issue by alqu** [koajs/locales#10]
Hi -

this time no bug, only an idea:
Since there is Node v4.0 out, would it make sense to replace the line
```javascript
merge(resources[locale], resource);
```
in index.js, line 62 with 
```javascript
Object.assign(resources[locale], resource);
```
?

**Comment by fengmk2** [comment]
close by #12

**Comment by hotoo** [comment]
This is a good idea, @fengmk2 reopen this issue please.
