### ISSUE TITLE
How much performance saved, and how much readable lost?

### ISSUE THREAD

**Issue by hotoo** [koajs/locales#2]
https://github.com/koajs/locales/blob/1.0.2/index.js#L80-L109

**Comment by fengmk2** [comment]
You can see the benchmark result.

**Comment by matthewmueller** [comment]
How about just using: https://github.com/aheckmann/sliced

**Comment by hotoo** [comment]
I write a benchmark, it't not too slow than direct call in iojs-2, see PR #6

**Comment by fengmk2** [comment]
Great!
