### ISSUE TITLE
any plans to support loading locales from database?

### ISSUE THREAD

**Issue by geoffreyrobichaux** [koajs/locales#41]
I have 5+ different projects and I don't want to copy existing translations or pay to have them retranslated. Looking for ways to share locale translated text across projects and it seems database storage is how others have done it in rails land. What do you think for Koa?

**Comment by niftylettuce** [comment]
You could use `@ladjs/i18n` and [Lad](https://lad.js.org) and reference a common localization path/folder.

**Comment by geoffreyrobichaux** [comment]
Thanks, @niftylettuce . I appreciate the response. 

I'm hoping for something that can share localized content between rails apps and node apps. To retain a single entry, even maintained via a CMS, then recalled by any app to build views and partials to collect into the UI. 

Some of my backend services contain content too. Else the nested services may need to normalize on english, then translate/map at the last layer to the desired language. As I don't want to maintain the same strings across multiple apps that all use such words as "Approved" or other common text. 

While I could also use a submodule to share via npm, that also brings its own versioning burden.

No perfect solution, just looking for ideas on how to share strings.
