### ISSUE TITLE
some startup errors

### ISSUE THREAD

**Issue by alqu** [koajs/locales#8]
after installing koa-locales, I got the error message "Cannot find module 'merge-descriptors'".
Then I manually moved "merge-descriptors" from devDependencies to dependencies, and after hitting npm install in that folder "node_modules/koa-locales/" I get this:

```
.../node_modules/koa-locales/index.js:98
  app.context[functionName] = function (key, value) {

TypeError: Cannot set property '__' of undefined
```
I am stuck.

**Comment by fengmk2** [comment]
Yep, `merge-descriptors` should be in `dependencies`

**Comment by fengmk2** [comment]
@alqu please use koa-locales@1.3.1

**Comment by alqu** [comment]
ok,

now the error with the merge-descriptors dependency is solved. But... I still get this error:

```
.../node_modules/koa-locales/index.js:98
  app.context[functionName] = function (key, value) {
                            ^

TypeError: Cannot set property '__' of undefined

```
when I use it like this:
```javascript
'use strict'
// ...
const app = require('koa')()
const bodyParser = require('koa-bodyparser')
const locales = require('koa-locales')
// ...
app.use(locales({dirs: [__dirname + '/locales'], defaultLocale: 'de_DE'}))
// ...
```

**Comment by fengmk2** [comment]
@alqu Sorry for the README show the wrong usage.

Please change your codes to:

```js
'use strict'
// ...
const app = require('koa')()
const bodyParser = require('koa-bodyparser')
const locales = require('koa-locales')
// ...
locales(app, {dirs: [__dirname + '/locales'], defaultLocale: 'de_DE'})
// ...
```

**Comment by alqu** [comment]
Ah, OK, works perfect now! Thanks.
